- type: department
  id: Expedition
  description: department-Expedition-description
  color: "#21421e"
  roles:
  - FieldCommander
  - FieldTrooper
  - FieldScientist
  - FieldMedic
  - FieldEngineer
